name: Release to NuGet

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish NuGet
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set output
      id: vars
      #run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $RELEASE_VERSION
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: |
        echo $RELEASE_VERSION
        dotnet build -c Release -p:Version=$RELEASE_VERSION
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
    - name: Add github Repo
      run: dotnet nuget add source --username muchachopolo --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/muchachopolo/index.json"
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
